### ISSUE TITLE
🐛 Bug ➾ result of simulation is gone ?

### ISSUE THREAD

**Issue by zamrokk** [TezosTaqueria/taqueria#1939]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

trying to run the simulate command here  : https://docs.tezos.com/tutorials/dapp/part-1#simulate-a-call-on-your-smart-contract

because we had an output of the storage , now it is empty

```
=== For pokeGame.tz ===
┌─────────────┬────────┐
│ Contract    │ Result │
├─────────────┼────────┤
│ pokeGame.tz │ N/A    │
```

### 🆘 Steps to Reproduce?

just run the tutorial until this point and run the simulation

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### 💻 Operating System

Windows -> WSL

### 🕸️ System Architecture

None

### 🌮 Taqueria Version

0.62

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Thanks @zamrokk - looking into this now.

**Comment by zamrokk** [comment]
Hi @mweichert , Tim had also similar error. Could you have a look on it please ?
